name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build with Maven verify
        run: ./mvnw -B verify
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            target/*.jar
