name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: ResilientGroup/MavenSetup/.github/workflows/build.yml@1.3.2
    secrets: inherit
